[package]
name = "ftptest"
version = "0.1.0"
authors = ["jacobweir"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ftp_utils = { git = "https://github.com/jweir136/ftp_utils.git" }